import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import homeImg from "../images/coder.avif";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.imageWrapper}>
          <Image
            className={styles.homeImg}
            src={homeImg}
            alt="coder"
            width={158}
            height={158}
          />
        </div>
        <h1 className={styles.title}>Hunting Coder</h1>

        <p className={styles.description}>
          Blogs for hunting coders by a hunting coder. Website to solve all your
          coding queries.
        </p>

        <div>
          <h2 className={styles.popularBlogs}>Latest Blogs</h2>
          <div>
            <h3 className={styles.blogs}>How to learn Javascript in 2022</h3>
            <p>
              Javascript is the language used to design logics for a websites.
            </p>
          </div>

          <div>
            <h3 className={styles.blogs}>How to learn Javascript in 2022</h3>
            <p>
              Javascript is the language used to design logics for a websites.
            </p>
          </div>

          <div>
            <h3 className={styles.blogs}>How to learn Javascript in 2022</h3>
            <p>
              Javascript is the language used to design logics for a websites.
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
